services:
  frontend:
    image: 1880160/tp2-1880160-frontend:v1
    build:
      context: ./movies-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - movies-network

  backend:
    image: 1880160/tp2-1880160-backend:v1
    container_name: movies-backend
    build:
      context: ./movies-backend
    ports:
      - "8787:8787"
    depends_on:
      - mongodb
    networks:
      - movies-network
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://root:123456:localhost/movie-api-db?authSource=admin
      - SERVER_PORT=8787

  mongodb:
    image: mongo:8.0.6
    networks:
      - movies-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
      - db:/data/db
      - ./mongo-seed:/docker-entrypoint-initdb.d

volumes:
  db:

networks:
  movies-network:
    driver: bridge
